"""Static UI catalogs and default options for the dashboard."""

DEFAULT_SETTINGS = {
    "shortcuts": {
        "set_target": "T",
        "draw_line": "D",
        "erase_drawing": "E",
        "full_view": "F",
        "add_watchlist": "W",
        "prev_symbol": "Up",
        "next_symbol": "Down",
        "pan_left": "Left",
        "pan_right": "Right"
    },
    "chart_pan_step_bars": 1
}

DEFAULT_SCANNER_SETUPS = {
    "Setup 1": {
        "min_volume": 40000.0,
        "min_dollar_volume": 35000.0,
        "min_adr": 2.4,
        "min_growth_rank": 97.04,
        "min_trend_intensity": 90.0,
        "rules": [
            {"attribute": "volume", "operator": ">=", "threshold": 40000.0},
            {"attribute": "dollar_volume", "operator": ">=", "threshold": 35000.0},
            {"attribute": "adr_20", "operator": ">=", "threshold": 2.4},
            {"attribute": "growth_rank_1m", "operator": ">=", "threshold": 97.04},
            {"attribute": "trend_intensity", "operator": ">=", "threshold": 90.0},
        ]
    },
    "Setup 2": {
        "min_volume": 250000.0,
        "min_dollar_volume": 5000000.0,
        "min_adr": 3.0,
        "min_growth_rank": 95.0,
        "min_trend_intensity": 80.0,
        "rules": [
            {"attribute": "volume", "operator": ">=", "threshold": 250000.0},
            {"attribute": "dollar_volume", "operator": ">=", "threshold": 5000000.0},
            {"attribute": "adr_20", "operator": ">=", "threshold": 3.0},
            {"attribute": "growth_rank_1m", "operator": ">=", "threshold": 95.0},
            {"attribute": "trend_intensity", "operator": ">=", "threshold": 80.0},
        ]
    },
}

SCANNER_METRICS_LABELS = {
    "price": "Price",
    "volume": "Volume",
    "avg_volume_20d": "Avg Volume (20d)",
    "dollar_volume": "Dollar Volume",
    "avg_dollar_volume_20d": "Avg Dollar Volume (20d)",
    "price_history_days": "Price History Days",
    "adr_20": "ADR (20d, %)",
    "atr_14_pct": "ATR (14d, %)",
    "range_today_pct": "Daily Range (%)",
    "return_1w": "1-Week Return (%)",
    "return_1m": "1-Month Return (%)",
    "return_3m": "3-Month Return (%)",
    "return_6m": "6-Month Return (%)",
    "growth_rank_1m": "1-Month Growth Rank",
    "growth_rank_3m": "3-Month Growth Rank",
    "sma_20": "SMA (20d)",
    "ema_50": "EMA (50d)",
    "sma_200": "SMA (200d)",
    "above_sma_20": "Above SMA 20",
    "above_ema_50": "Above EMA 50",
    "ma_alignment": "MA Alignment (20 > 50 > 200)",
    "distance_from_20ma_pct": "Dist from SMA 20 (%)",
    "distance_from_50ema_pct": "Dist from EMA 50 (%)",
    "trend_intensity": "Trend Intensity",
    "trend_score": "Trend Score",
    "relative_volume": "Relative Volume",
    "volume_expansion": "Volume Expansion",
    "volume_dryup_ratio": "Volume Dryup Ratio",
    "high_20d": "20-day High",
    "high_50d": "50-day High",
    "high_252d": "52-week High",
    "close_to_52w_high_pct": "Dist to 52-week High (%)",
    "distance_to_20d_high_pct": "Dist to 20-day High (%)",
    "breakout_20d": "Breakout (20d)",
    "breakout_50d": "Breakout (50d)",
    "consolidation_range_10d_pct": "Consolidation Range (10d, %)",
    "consolidation_tightness": "Consolidation Tightness",
    "pullback_depth_pct": "Pullback from 50d High (%)",
    "extension_10ma_pct": "Extension from SMA 10 (%)",
    "extension_20ma_pct": "Extension from SMA 20 (%)",
    "extension_50ema_pct": "Extension from EMA 50 (%)",
    "return_3d": "3-Day Return (%)",
    "return_5d": "5-Day Return (%)",
    "consecutive_up_days": "Consecutive Up Days",
    "parabolic_flag": "Parabolic Extension",
    "rs_score_252": "Relative Strength Score (252)",
    "rs_above_sma_50": "RS Above SMA 50",
    "rs_slope_20d": "RS Slope (20d)",
    "score": "Final Score",
}

DEFAULT_TAB_OPTIONS = {
    "dashboard": True,
    "scanner": True,
    "watchlist": True,
    "charts": False,
    "tradingview": True,
    "intraday_charts": False,
    "trade_plan": True,
}

FILTER_CATALOG = [
    ("Identification", "symbol", "symbol", "Stock ticker.", "Required"),
    ("Identification", "name", "name", "Company name if available; otherwise use symbol.", "Optional"),
    ("Basic tradability", "price", "price", "Latest close price. Avoids penny stocks.", "Hard filter: >= 5; quality filter: >= 10"),
    ("Basic tradability", "volume", "volume", "Latest daily share volume.", "Minimum: >= 40,000; better: >= 100,000"),
    ("Basic tradability", "avg_volume_20d", "avg_volume_20d", "20-day average daily volume. More stable than one-day volume.", "Minimum: >= 100,000; quality: >= 500,000"),
    ("Basic tradability", "dollar_volume", "dollar_volume", "price Ã— volume. Measures tradable money flow.", "Minimum: >= 500,000; quality: >= 1,000,000"),
    ("Basic tradability", "avg_dollar_volume_20d", "avg_dollar_volume_20d", "20-day average dollar volume. Best liquidity filter.", "Minimum: >= 1M; quality: >= 5M—10M"),
    ("Basic tradability", "price_history_days", "price_history_days", "Number of usable OHLCV rows.", "Minimum: >= 65; ideal: >= 252"),
    ("Volatility", "adr_20", "adr_20", "20-day average daily range percentage. Captures swing-trading movement.", "Minimum: >= 2.4%; stricter: >= 3.0%; caution if > 12—15%"),
    ("Volatility", "atr_14_pct", "atr_14_pct", "14-day ATR as percent of price. Alternative volatility measure.", "Minimum: >= 2.0%; preferred: 2.5—10%"),
    ("Volatility", "range_today_pct", "range_today_pct", "Today’s high-low range as percent of previous close.", "Ranking metric; EP flag if >= adr_20"),
    ("Momentum / growth", "return_1w", "return_1w", "5-trading-day return.", "Ranking only; avoid extreme chase if > 25—30%"),
    ("Momentum / growth", "return_1m", "return_1m", "21-trading-day return. Main short-term leadership metric.", "Ranking only; used to calculate growth_rank_1m"),
    ("Momentum / growth", "return_3m", "return_3m", "63-trading-day return. Confirms sustained strength.", "Ranking only; used to calculate growth_rank_3m"),
    ("Momentum / growth", "return_6m", "return_6m", "126-trading-day return. Longer-term trend strength.", "Ranking only; useful score input"),
    ("Momentum / growth", "growth_rank_1m", "growth_rank_1m", "Cross-sectional percentile rank of 1-month return.", "Strict breakout: >= 97; looser: >= 95"),
    ("Momentum / growth", "growth_rank_3m", "growth_rank_3m", "Cross-sectional percentile rank of 3-month return.", "Quality filter: >= 90—95"),
    ("Trend", "sma_20", "sma_20", "20-day simple moving average.", "Reference value"),
    ("Trend", "ema_50", "ema_50", "50-day exponential moving average.", "Reference value"),
    ("Trend", "sma_200", "sma_200", "200-day simple moving average. Long-term trend filter.", "Optional: price above sma_200 preferred"),
    ("Trend", "above_sma_20", "above_sma_20", "Checks whether price is above 20MA.", "Breakout filter: True"),
    ("Trend", "above_ema_50", "above_ema_50", "Checks whether price is above 50EMA.", "Breakout filter: True"),
    ("Trend", "ma_alignment", "ma_alignment", "Checks whether shorter MA is above longer MA. Example: sma_20 > ema_50.", "Preferred: True"),
    ("Trend", "distance_from_20ma_pct", "distance_from_20ma_pct", "Price extension above/below 20MA. Prevents chasing.", "Preferred: 0—20%; hard max: <= 25%"),
    ("Trend", "distance_from_50ema_pct", "distance_from_50ema_pct", "Price extension above/below 50EMA. Measures trend strength and overextension.", "Preferred: 0—35%; caution if > 50%"),
    ("Trend", "trend_intensity", "trend_intensity", "Scaled score based on how strongly price is above 50EMA.", "Minimum: >= 80; strict: >= 90"),
    ("Trend", "trend_score", "trend_score", "Improved trend score after penalizing overextension.", "Minimum: >= 70; strict: >= 75—80"),
    ("Volume quality", "relative_volume", "relative_volume", "Latest volume divided by 20-day average volume.", "Candidate: >= 1.2; breakout confirmation: >= 1.5"),
    ("Volume quality", "volume_expansion", "volume_expansion", "Boolean flag for strong volume above average.", "True if volume >= 1.5 Ã— avg_volume_20d"),
    ("Volume quality", "volume_dryup_ratio", "volume_dryup_ratio", "5-day average volume divided by 20-day average volume. Finds quiet consolidation.", "Good base: < 0.8; very tight: < 0.6"),
    ("Breakout / consolidation", "high_20d", "high_20d", "Highest high over 20 trading days.", "Reference pivot"),
    ("Breakout / consolidation", "high_50d", "high_50d", "Highest high over 50 trading days.", "Reference pivot"),
    ("Breakout / consolidation", "high_252d", "high_252d", "52-week high.", "Reference leadership level"),
    ("Breakout / consolidation", "close_to_52w_high_pct", "close_to_52w_high_pct", "Latest close as percent of 52-week high.", "Minimum: >= 80%; quality: >= 85—90%"),
    ("Breakout / consolidation", "distance_to_20d_high_pct", "distance_to_20d_high_pct", "Distance from current price to 20-day high. Measures breakout proximity.", "Actionable: <= 5%; loose: <= 10%"),
    ("Breakout / consolidation", "breakout_20d", "breakout_20d", "Price closes above prior 20-day high.", "Trigger flag: True"),
    ("Breakout / consolidation", "breakout_50d", "breakout_50d", "Price closes above prior 50-day high.", "Stronger trigger flag: True"),
    ("Breakout / consolidation", "consolidation_range_10d_pct", "consolidation_range_10d_pct", "10-day high-low range as percent of close. Measures tightness.", "Lower is better; usually <= 10—20% depending on ADR"),
    ("Breakout / consolidation", "consolidation_tightness", "consolidation_tightness", "consolidation_range_10d_pct / adr_20. Normalizes tightness by volatility.", "Good: <= 3; very tight: <= 2"),
    ("Breakout / consolidation", "pullback_depth_pct", "pullback_depth_pct", "Distance from recent high to current close. Avoids broken patterns.", "Preferred: <= 20—25%"),
    ("Overextension", "extension_10ma_pct", "extension_10ma_pct", "Price extension from 10MA.", "Preferred: <= 15—20%"),
    ("Overextension", "extension_20ma_pct", "extension_20ma_pct", "Price extension from 20MA. Main anti-chase filter.", "Preferred: <= 20%; hard max: <= 25%"),
    ("Overextension", "extension_50ema_pct", "extension_50ema_pct", "Price extension from 50EMA. Identifies parabolic risk.", "Preferred: <= 35—40%; caution if > 50%"),
    ("Overextension", "return_3d", "return_3d", "3-day return. Flags short-term spike.", "Warning if > 20—25%"),
    ("Overextension", "return_5d", "return_5d", "5-day return. Flags short-term parabolic move.", "Warning if > 30—40%"),
    ("Overextension", "consecutive_up_days", "consecutive_up_days", "Number of consecutive closes above prior close.", "Warning if >= 4; caution if >= 5"),
    ("Overextension", "parabolic_flag", "parabolic_flag", "Combined flag for extreme extension or fast multi-day spike.", "Must be False for normal breakout scanner"),
    ("Relative strength", "rs_score_252", "rs_score_252", "Percentile rank of stock/SPY relative strength over 252 days.", "Minimum: >= 70; quality: >= 80"),
    ("Relative strength", "rs_above_sma_50", "rs_above_sma_50", "Relative strength line above its 50-day SMA.", "Preferred: True"),
    ("Relative strength", "rs_slope_20d", "rs_slope_20d", "20-day change in stock/SPY relative strength.", "Preferred: > 0"),
    ("Final scoring", "score", "score", "Weighted ranking score from selected metrics. Not a raw yfinance field.", "Rank descending; no hard threshold unless needed")
]

