"""Stable database constants with no runtime namespace synchronization."""

import logging
import re

_MYSQL_IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z0-9_]+$")
_MYSQL_HOST_FORBIDDEN_CHARACTERS = frozenset("/\\@?#")
MYSQL_CONNECT_TIMEOUT_SECONDS = 3
MYSQL_READ_WRITE_TIMEOUT_SECONDS = 15
MYSQL_POOL_RECYCLE_SECONDS = 1800
CACHE_QUERY_SYMBOL_CHUNK_SIZE = 200
HOURLY_CACHE_QUERY_SYMBOL_CHUNK_SIZE = 25
SCANNER_QUERY_SYMBOL_CHUNK_SIZE = 500
SCANNER_METRIC_WRITE_CHUNK_SIZE = 250
SCANNER_METRICS_CACHE_VERSION = 1
CHART_INDICATOR_CACHE_VERSION = 1
REFERENCE_SYMBOL = "SPY"
logger = logging.getLogger("src.infrastructure.database")
